const solicitudes = [
  {
    nombre: "Rosa",
    apellido: "Benites",
    email: "berrios.ignacio@cintron.com",
    telefono: "3142501508",
    departamento: "Santander",
    ciudad: "Landázuri",
    colegio: "INSTITUTO COLOMBO VENEZOLANO - CECOVE.",
    nit: "14.64.120.141",
    direccion: "KR 4 7 07",
    enfasis: "PROGRAMA PARA JÓVENES EN EXTRAEDAD Y ADULTOS",
    token: "a15i90b03hb57",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "Julian",
    apellido: "Durán",
    email: "caballero.jose@terra.com",
    telefono: "3198233644",
    departamento: "Risaralda",
    ciudad: "Mistrató",
    colegio: "INST EDU INST MISTRATO",
    nit: "55.217.200.248",
    direccion: "CL 8 5 35",
    enfasis: "Bachillerato académico",
    token: "f8f8cc2g53g1",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "Juan Jose",
    apellido: "Muñoz",
    email: "jsanchez@lazaro.com",
    telefono: "3105182892",
    departamento: "Caldas",
    ciudad: "Manizales",
    colegio: "INSTITUCIÓN EDUCATIVA RURAL MARIA GORETTI",
    nit: "153.114.52.202",
    direccion: "BAJO TABLAZO",
    enfasis: "Bachillerato académico",
    token: "0bgj1bha395i3b",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "Noelia",
    apellido: "Vazquez",
    email: "santiago.fernandez@hotmail.com",
    telefono: "3101226290",
    departamento: "Cundinamarca",
    ciudad: "Facatativá",
    colegio: "I.E.M MANABLANCA",
    nit: "145.231.179.153",
    direccion: "IND BARRIO MANABLANCA SECTOR 2",
    enfasis: "Bachillerato académico",
    token: "89b6e92083if7",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "María Antonia",
    apellido: "Esteban",
    email: "xmontalvo@soto.es",
    telefono: "3165377665",
    departamento: "Cundinamarca",
    ciudad: "Fusagasugá",
    colegio: "LIC INFANTIL SANTA INES",
    nit: "205.136.237.102",
    direccion: "CL 5 3 27",
    enfasis: "Básica Primaria",
    token: "d45254gca6jh6",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "Carlos",
    apellido: "Bravo",
    email: "vibanez@yahoo.es",
    telefono: "3120996584",
    departamento: "Cundinamarca",
    ciudad: "Soacha",
    colegio: "INSTITUTO TECNICO LOS PINOS",
    nit: "133.29.197.75",
    direccion: "KR 44 A ESTE 48 31",
    enfasis: "Básica Secundaria",
    token: "a92jcdgh8ib3",
    rol: "colegio",
    cargo: "docente",
    materia: "Español"
  },
  {
    nombre: "María Victoria",
    apellido: "Alvarez",
    email: "leo94@camacho.org",
    telefono: "3182832152",
    departamento: "Bogotá D.C.",
    ciudad: "Bogotá D.C.",
    colegio: "GIMNASIO FEMENINO",
    nit: "141.44.125.130",
    direccion: "KR 7 128 40",
    enfasis: "Bachillerato académico",
    token: "1ed7hj0hh50dj",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "María Pilar",
    apellido: "Santiago",
    email: "rueda.gabriela@yahoo.com",
    telefono: "3113092027",
    departamento: "Bogotá D.C.",
    ciudad: "Bogotá D.C.",
    colegio: "COLEGIO REPUBLICA DE COLOMBIA (IED)",
    nit: "255.77.124.247",
    direccion: "CL 68 69 10",
    enfasis: "Bachillerato académico",
    token: "f52a89ii6f96",
    rol: "colegio",
    cargo: "docente",
    materia: "Matemáticas"
  },
  {
    nombre: "Ángela",
    apellido: "Lorenzo",
    email: "tsaenz@carmona.com",
    telefono: "3219096100",
    departamento: "Bogotá D.C.",
    ciudad: "Bogotá D.C.",
    colegio: "COLEGIO CEDID SAN PABLO (IED)",
    nit: "232.219.72.75",
    direccion: "IND TR. 6A NO.6A-30 (BOSA)",
    enfasis: "Bachillerato académico",
    token: "i2b9g6ba80ij",
    rol: "colegio",
    cargo: "docente",
    materia: "Inglés"
  },
  {
    nombre: "Julian",
    apellido: "Suarez",
    email: "ojeda.juanjose@latinmail.com",
    telefono: "3017358925",
    departamento: "Córdoba",
    ciudad: "Lorica",
    colegio: "INSTITUTO INFANTIL BUENAVENTURA",
    nit: "238.164.188.19",
    direccion: "CR 28 NØ CLL 27 - A30",
    enfasis: "Básica Primaria",
    token: "cgfb4jg3gfh8c",
    rol: "colegio",
    cargo: "docente",
    materia: "Sociales"
  },
];

export default solicitudes
